language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.0
sudo: false
env:
  - MIX_ENV=test
script: mix coveralls.travis
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0